<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>L20: Promise</title>
  </head>
  <body>
    <script>
      // 1. Cosa sono le promise?
      // promise: rappresentanza di uno stato, dell'outcome di un'operazione asincrona
      // stato: pending, fullfilled o rejected
      // promessa di ritornare un valore che il programma ci da
      // non sappiamo nulla sul tipo di risposta
      // sappiamo solo che in modo asincrono ci verrà dato qualcosa

      // 2. Il probalema con le callback
      // chooseToppings(function (toppings) {
      //   placeOrder(
      //     toppings,
      //     function (order) {
      //       collectOrder(
      //         order,
      //         function (pizza) {
      //           eatPizza(pizza);
      //         },
      //         failureCallback
      //       );
      //     },
      //     failureCallback
      //   );
      // }, failureCallback);

      // 3. Il miglioramento tramite promise
      // 4. Sintassi della promise
      // 5. Risposta in caso di fallimento
      // 6. Chaining

      // usando ES6
      // sintassi con promise
      // chooseToppings()
      //   .then(function (toppings) {
      //     // dopo che chooseToppings() è stato eseguito eseguo la f anonima che ritorna la f placeOrder()
      //     return placeOrder(toppings);
      //   })
      //   .then(function (order) {
      //     // come quella sopra
      //     return collectOrder(order);
      //   })
      //   .then(function (pizza) {
      //     eatPizza(pizza);
      //   })
      //   .catch(failureCallback); // 1 sola failureCallback

      // // usando ES6
      // chooseToppings()
      //   .then((toppings) => {
      //     return placeOrder(toppings);
      //   })
      //   .then((order) => {
      //     return collectOrder(order);
      //   })
      //   .then((pizza) => {
      //     eatPizza(pizza);
      //   })
      //   .catch(failureCallback);

      // aggiunta di un immagine grazie al fetch
      // aggiunta dinamica
      fetch('coffee.jpg')
        .then(response => {
          return response.blob(); // .blob() si usa quando ho un binary large object
        })
        // agganciando un .then con un punto si tratta di chaining
        .then(myBlob => {
          let objectURL = URL.createObjectURL(myBlob);
          let image = document.createElement('img');
          image.src = objectURL;
          document.body.appendChild(image);
        })
        .catch(e => {
          console.log(
            'There has been a problem with your fetch operation: ' + e.message
          );
        });

      // 7. Costruire promise custom
      // 8. Rifiutare promise custom
      // nuovo oggetto
      // che deve andare a seguire una f
      // la promise può avere 2 risultati: risolta(resolved) o rigettata(rejected)
      // questo esempio è per sintassi, non ha senso
      // let timeoutPromise = new Promise((resolve, reject) => {
      //   setTimeout(() => {
      //     resolve("Success!");
      //   }, 2000);
      // });
      // sintassi super basica
      let prova = new Promise((resolve, reject) => {
        resolve();
      });

      // esempio vero
      // è come se specificassi il comportamento basandmi su ciò che accade
      function timeoutPromise(message, interval) {
        return new Promise((resolve, reject) => {
          // la funzione creata deve restituire una promise
          // la promise deve fare qualcosa (resolve, reject)
          if (message === '' || typeof message !== 'string') {
            reject('Message is empty or not a string');
          } else if (interval < 0 || typeof interval !== 'number') {
            reject('Interval is negative or not a number');
          } else {
            setTimeout(() => {
              resolve(message);
            }, interval);
          }
        });
      }

      // con le promise custom gestiamo manualmente gli errori
      // stringa vuota per generare volutamente l'errore
      timeoutPromise('', 1000)
        .then(message => {
          alert(message);
        })
        .catch(e => {
          // e è riferito alla fase di reject della promise
          console.log('Error: ' + e);
        });
    </script>
  </body>
</html>
